import type { Metadata } from "next";
import "./admin.css";
import AdminSideNavbar from "./components/ui/AdminSideNavbar";
import AdminTopNanbar from "./components/ui/AdminTopNanbar";

export const metadata: Metadata = {
  title: "Create ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main>
        <AdminTopNanbar />
        <AdminSideNavbar />
        {children}
      </main>
    </>
  );
}
