import type { Metadata } from "next";
import "./admin.css";
import AdminSideNavbar from "./components/ui/AdminSideNavbar";
import AdminTopNanbar from "./components/ui/AdminTopNanbar";

export const metadata: Metadata = {
  title: "Create ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {/* 🔝 Top Navbar */}
      <AdminTopNanbar />

      {/* 📌 Sidebar */}
      <AdminSideNavbar />

      {/* 📦 Main Content */}
      <main
        className={`
          min-h-screen
          mt-16
          ml-16 lg:ml-64
          p-4 md:p-6
          transition-all duration-300
        `}
      >
        {children}
      </main>
    </div>
  );
}