import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../../components/Navbar";
 
 

export const metadata: Metadata = {
  title: "Create ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
       <main >
        <Navbar />
        {children}
      </main>
    </>
   );
}
